### ISSUE TITLE
Falta Midas.dll ao abrir o VisualizaDTS

### ISSUE THREAD

**Issue by italosouza** [AndreLuisCelestino/PluginDB1#1]
não está sendo possível abrir  o VisualizaDTS devido a ausência da biblioteca midas.dll, observo que seria interessante não depender da biblioteca registrada no sistema, pois em alguns caso podemos ter aplicações usando versões diferentes.
![dll](https://cloud.githubusercontent.com/assets/4523975/18205256/66980d9e-70f7-11e6-938c-bc63874ae11d.PNG)

**Comment by AndreLuisCelestino** [comment]
Obrigado por reportar o problema, Italo.
Já adicionei o arquivo "midas.dll" no script do instalador.
